//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCRemote.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCRemote.UI.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#已经停止关闭您的计算机。.
        /// </summary>
        internal static string AbortShutdownCommand_Comment {
            get {
                return ResourceManager.GetString("AbortShutdownCommand_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#将会在5分钟之后帮您重启您的计算机。如果需要终止重启，请发微博：终止关机$$任意内容。.
        /// </summary>
        internal static string RestartCommand_Comment {
            get {
                return ResourceManager.GetString("RestartCommand_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#将会在5分钟之后帮您关闭您的计算机。如果需要终止重启，请发微博：终止关机$$任意内容。.
        /// </summary>
        internal static string ShutdownCommand_Comment {
            get {
                return ResourceManager.GetString("ShutdownCommand_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#已经帮您减小音量。加大音量，请发微博：加大音量$$任意内容。.
        /// </summary>
        internal static string VolDecCommand_Comment {
            get {
                return ResourceManager.GetString("VolDecCommand_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#已经帮您加大音量。减小音量，请发微博：减小音量$$任意内容。.
        /// </summary>
        internal static string VolIncCommand_Comment {
            get {
                return ResourceManager.GetString("VolIncCommand_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#已经将您的计算机设为静音。取消静音，请发微博：取消静音$$任意内容。.
        /// </summary>
        internal static string VolMuteCommand_Comment {
            get {
                return ResourceManager.GetString("VolMuteCommand_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PC遥控器#已经帮您取消静音。静音，请发微博：静音$$任意内容。.
        /// </summary>
        internal static string VolUnMuteCommand_Comment {
            get {
                return ResourceManager.GetString("VolUnMuteCommand_Comment", resourceCulture);
            }
        }
    }
}
